"""Add scheduler_locks table

Revision ID: 005_add_scheduler_locks
Revises: 004_add_article_categories_many_to_many
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_scheduler_locks'
down_revision: Union[str, None] = '004_article_categories'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lock_name', sa.String(length=100), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lock_name')
    )
    op.create_index(op.f('ix_scheduler_locks_expires_at'), 'scheduler_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_scheduler_locks_lock_name'), 'scheduler_locks', ['lock_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_locks_lock_name'), table_name='scheduler_locks')
    op.drop_index(op.f('ix_scheduler_locks_expires_at'), table_name='scheduler_locks')
    op.drop_table('scheduler_locks')
    # ### end Alembic commands ###
